source "https://rubygems.org"

gem "rails", "3.2.13"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem "sass-rails",   "~> 3.2.3"
  gem "coffee-rails", "~> 3.2.1"

  gem "uglifier", ">= 1.0.3"

  gem "bootstrap-sass", "~> 2.3"
end

gem "country-select"
gem "formtastic"
gem "formtastic-plus-bootstrap", path: "../"
gem "quiet_assets"
